"""initial_schema

Revision ID: 08ebf1a02b00
Revises: 
Create Date: 2026-04-27 22:00:14.917613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ebf1a02b00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=False),
    sa.Column('zip_code_prefix', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('geolocations',
    sa.Column('geolocation_id', sa.String(length=36), nullable=False),
    sa.Column('zip_code_prefix', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('geolocation_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('category_name_en', sa.String(length=100), nullable=True),
    sa.Column('description_length', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('shipping_limit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('freight_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_table('order_payments',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.create_table('order_reviews',
    sa.Column('order_review_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_reviews')
    op.drop_table('order_payments')
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('sellers')
    op.drop_table('products')
    op.drop_table('geolocations')
    op.drop_table('customers')
    # ### end Alembic commands ###
